import Head from 'next/head'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'

// import products from '../../src/products.json'
import { fromImageToUrl, API_URL } from 'utils/urls'
import { twoDecimals } from 'utils/format'


export default function Home({products}) {
  console.log(products)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {products.data.map(product => (
        <div key={product.attributes.name} className={styles.product}>
          <Link href={`/products/${product.attributes.slug}`}>
            <div className={styles.product__Row}>
              <div className={styles.product__ColImg}>
                <img src={fromImageToUrl(product.attributes.image)}/>
              </div>
              <div className={styles.product__Col}>
                {product.attributes.name} £{twoDecimals(product.attributes.price)}
              </div>
            </div>
          </Link>
        </div>
      ))}
    </>
  )
}

export async function getStaticProps() {
  try {
    // fetch the products
    const product_res = await fetch(`${API_URL}/api/products?populate=*`)
    const products = await product_res.json()

    if (errors || !products) {
      return { notFound: true };
    }
      // return the products as props
    return {
      props: {
        products
      }
    }
  } catch (error) {
    return {notFound: true}
  }
  


}